FROM node:22.11.0-slim

ARG HTTPS_KEY
ARG HTTPS_CERT
ARG VITE_BACKEND_URL
ARG VITE_GOOGLE_CLIENT_ID

ENV HTTPS_KEY=$HTTPS_KEY
ENV HTTPS_CERT=$HTTPS_CERT
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID

WORKDIR /client

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 80

CMD ["npm", "run", "preview"]
