name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Images
        run: |
          docker build --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} --build-arg VITE_BACKEND_URL=${{ vars.VITE_BACKEND_URL }} -t ${{ vars.DOCKER_USERNAME }}/work-wise-client ./
          docker push ${{ vars.DOCKER_USERNAME }}/work-wise-client
  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Trigger Deployment
        run: |
          curl --fail -X POST ${{ vars.DEPLOY_API_URL }} -H "Authorization: Bearer ${{ secrets.DEPLOY_API_TOKEN }}"
